### ISSUE TITLE
router-view not working

### ISSUE THREAD

**Issue by mahmutatmaca** [AsaoluElijah/vue-electron#2]
Hi can i use with hash '#' url in project?

**Comment by AsaoluElijah** [comment]
Hi. Could you please describe the problem in detail. Probably with code samples too 🙏

**Comment by mahmutatmaca** [comment]
I included to vua-element-admin and load index page
![WhatsApp Image 2022-09-22 at 00 27 53](https://user-images.githubusercontent.com/4445339/191613498-56b48a68-09f1-4a6a-913a-507b45b6a56b.jpeg)
but when click to subpage from menu not load page. writen "$route" value to screen
![WhatsApp Image 2022-09-22 at 00 28 57](https://user-images.githubusercontent.com/4445339/191613496-9022cef6-51c9-4ac7-971b-142a8c199955.jpeg)

**Comment by mahmutatmaca** [comment]
ok, i fixed thank you for speedy answer
